{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kusaanko",
    "module": "imgui-java-natives-linux",
    "version": "d9503d",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "imgui-java-natives-linux-d9503d.jar",
          "url": "imgui-java-natives-linux-d9503d.jar",
          "size": 1700591,
          "sha512": "0f17ff2d76d297784904efca84f44e22134d00a2a3da38a4c6a1a7b6d699ed4f6c94981f4a07e7c210c331b153edffaa1809f6f28fb1e69642a26a24affdde23",
          "sha256": "e74e49d981641cd10464bf8e3e461af886e4ee84a8985830863ce6efed069bfa",
          "sha1": "1300d9c7e662f964be911412492227818e6cec96",
          "md5": "44792bc6851756c673eaf8e735f8e940"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-java-natives-linux-d9503d.jar",
          "url": "imgui-java-natives-linux-d9503d.jar",
          "size": 1700591,
          "sha512": "0f17ff2d76d297784904efca84f44e22134d00a2a3da38a4c6a1a7b6d699ed4f6c94981f4a07e7c210c331b153edffaa1809f6f28fb1e69642a26a24affdde23",
          "sha256": "e74e49d981641cd10464bf8e3e461af886e4ee84a8985830863ce6efed069bfa",
          "sha1": "1300d9c7e662f964be911412492227818e6cec96",
          "md5": "44792bc6851756c673eaf8e735f8e940"
        }
      ]
    }
  ]
}
