{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kusaanko",
    "module": "imgui-java-natives-windows",
    "version": "7dc310",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "imgui-java-natives-windows-7dc310.jar",
          "url": "imgui-java-natives-windows-7dc310.jar",
          "size": 1860468,
          "sha512": "c1af47ec7560e620245163ab0158ea44bac5a63fcb39d3b855396b0d41acea490e7194a64c953eabf1e27934336719475d7977b4c6df12200db042197e17016a",
          "sha256": "649e4d454ba6c87cdbfd812a28924094f6767052eedf121203a302b6ae494e0b",
          "sha1": "0ba0fdd54a7fcb5e4a3adb91bed38dcefa53f983",
          "md5": "3dd2d81ef7a9fe647ee3b1b17023737b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-java-natives-windows-7dc310.jar",
          "url": "imgui-java-natives-windows-7dc310.jar",
          "size": 1860468,
          "sha512": "c1af47ec7560e620245163ab0158ea44bac5a63fcb39d3b855396b0d41acea490e7194a64c953eabf1e27934336719475d7977b4c6df12200db042197e17016a",
          "sha256": "649e4d454ba6c87cdbfd812a28924094f6767052eedf121203a302b6ae494e0b",
          "sha1": "0ba0fdd54a7fcb5e4a3adb91bed38dcefa53f983",
          "md5": "3dd2d81ef7a9fe647ee3b1b17023737b"
        }
      ]
    }
  ]
}
