{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kusaanko",
    "module": "imgui-java-binding",
    "version": "7dc310",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "imgui-java-binding-7dc310.jar",
          "url": "imgui-java-binding-7dc310.jar",
          "size": 147021,
          "sha512": "fff67d908542da008e951e066cdec0d8f23d81c774a250b2086eee0dda0f75c75614c738293fd774fd5f8c811cb0320a7077ed8d8995d4e7d7edf8b319744723",
          "sha256": "c1e64c072f2b0294c463258041693cd1f065481078fb6f05feab514d4293faf5",
          "sha1": "737264287713fbfbea803a6f9b6e788042ebb0b4",
          "md5": "c08fc6b89fe1852a5b6bc5405abd538d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-java-binding-7dc310.jar",
          "url": "imgui-java-binding-7dc310.jar",
          "size": 147021,
          "sha512": "fff67d908542da008e951e066cdec0d8f23d81c774a250b2086eee0dda0f75c75614c738293fd774fd5f8c811cb0320a7077ed8d8995d4e7d7edf8b319744723",
          "sha256": "c1e64c072f2b0294c463258041693cd1f065481078fb6f05feab514d4293faf5",
          "sha1": "737264287713fbfbea803a6f9b6e788042ebb0b4",
          "md5": "c08fc6b89fe1852a5b6bc5405abd538d"
        }
      ]
    }
  ]
}
