{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kusaanko",
    "module": "imgui-java-natives-macos-ft",
    "version": "362c17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "imgui-java-natives-macos-ft-362c17.jar",
          "url": "imgui-java-natives-macos-ft-362c17.jar",
          "size": 2821730,
          "sha512": "4980b64310b3a10622376997341db0af21f810f43386cfa0cc2affaed3c81deeca6d64b4c2a674609ef34444f5aa151ac6bd436814236308b7564e4ea8013e18",
          "sha256": "da96206cdbb12f95b7b4a968391be88cd1ae580c83debc2badba4c814ab60506",
          "sha1": "e25dc014041dce7f58d19ebbf174d2f1b6438bcb",
          "md5": "b88a1de898071775a0462c027e88b630"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-java-natives-macos-ft-362c17.jar",
          "url": "imgui-java-natives-macos-ft-362c17.jar",
          "size": 2821730,
          "sha512": "4980b64310b3a10622376997341db0af21f810f43386cfa0cc2affaed3c81deeca6d64b4c2a674609ef34444f5aa151ac6bd436814236308b7564e4ea8013e18",
          "sha256": "da96206cdbb12f95b7b4a968391be88cd1ae580c83debc2badba4c814ab60506",
          "sha1": "e25dc014041dce7f58d19ebbf174d2f1b6438bcb",
          "md5": "b88a1de898071775a0462c027e88b630"
        }
      ]
    }
  ]
}
