{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kusaanko",
    "module": "imgui-java-binding",
    "version": "2a2819",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "imgui-java-binding-2a2819.jar",
          "url": "imgui-java-binding-2a2819.jar",
          "size": 149633,
          "sha512": "f8bf1461603738ed7392192e21f8d2ec045430bbb3ed9b6b2adada377c4265426ab8b9ddec5c48c192370cd405a686d59c49cc1ce3004fb775ba2a29a3827051",
          "sha256": "6f60e6add111badbdc75fd9de9eed1dcc79914d7827e369edb1c345c241eeb78",
          "sha1": "89836115e3aae39273af5f5350a98bb08bd11e7c",
          "md5": "9e0ea965346ff264f87e2fbfea832d8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "imgui-java-binding-2a2819.jar",
          "url": "imgui-java-binding-2a2819.jar",
          "size": 149633,
          "sha512": "f8bf1461603738ed7392192e21f8d2ec045430bbb3ed9b6b2adada377c4265426ab8b9ddec5c48c192370cd405a686d59c49cc1ce3004fb775ba2a29a3827051",
          "sha256": "6f60e6add111badbdc75fd9de9eed1dcc79914d7827e369edb1c345c241eeb78",
          "sha1": "89836115e3aae39273af5f5350a98bb08bd11e7c",
          "md5": "9e0ea965346ff264f87e2fbfea832d8b"
        }
      ]
    }
  ]
}
